### ISSUE TITLE
Time Elapsed (hh:mm:ss.fff)?

### ISSUE THREAD

**Issue by nurbles** [mike-ward/VSColorOutput#100]
I like having the Time Elapsed shown when my builds complete.  I am curious why it is now showing the format used "(hh:mm:ss.fff)" after the actual time value?  For example:

![TimeElapsed](https://user-images.githubusercontent.com/14079927/69076278-21691000-0a01-11ea-84d9-af719bf38fcb.png)

Do we really _need_ to see the format here?  It _might_ be a useful reminder **if** we were allowed enter different formats, but as-is, it just obscures (slightly) the info we are looking for.

**Comment by mike-ward** [comment]
Probably because someone bugged me to do it sometime in the distant past. Does seem odd to have it there.

**Comment by mike-ward** [comment]
Scheduled for 2.7 release.
