### ISSUE TITLE
Extension not listed for VS2015, VS2017

### ISSUE THREAD

**Issue by nzain** [mike-ward/VSColorOutput#104]
Using VS2017 Professional. I can manually install 2.6.4. I cannot install 2.7 (guess it only supports 2019, which is ok). However, the extension is not visible within Visual Studio anymore because you publish only the latest vsix package. Took me a while to find out that this extension still exists!

You could publish a VSColorOutput2015 extension, a VSColorOutput2017.vsix and another one for 2019. Just like [Productivity Power Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ProductivityPowerPack2017) for example.

Related: #89

**Comment by mike-ward** [comment]
Ah, such a simple solution. Thanks.

**Comment by mike-ward** [comment]
Well maybe not. I have to rebuild the package ids and names. Bummer.
