### ISSUE TITLE
"error.cshtml" false error

### ISSUE THREAD

**Issue by DavidDeSloovere** [mike-ward/VSColorOutput#11]
Another one for the hardcoded classifications:
Error.cshtml is a view in my project and lines with this filename are displayed 'Error', should be 'Build text'.

I wonder if the regex should be smart enough to catch more file types, fex. Error.cs
The filename will always follow a path.

**Comment by mike-ward** [comment]
Any ideas for a regex to catch these?

**Comment by DavidDeSloovere** [comment]
I think we need to find `\Error*.*` Don't know if we need to find both slash and backslash

This `\\Error.*\.[\w]` should match the first 3, but not the last one in this test:

    C:\TfsProjects\Error.cshtml
    C:\TfsProjects\Error.cs
    C:\TfsProjects\ErrorController.cs
    This \Error. Does not match

Tried it this http://regexstorm.net/tester

**Comment by matthewpavkov** [comment]
Here is another similar example. These show in red in the build output:

```
D:\ONOSYS\ONOSYSv4\12\21.RTPConversion\Dev\ONOSYS.Api\Services\DatabaseExceptionLogger.cs(142,21,142,33): warning CS1591: Missing XML comment for publicly visible type or member 'DatabaseExceptionLogger.LogException(Exception)'

D:\ONOSYS\ONOSYSv4\12\21.RTPConversion\Dev\ONOSYS.Api\Services\DatabaseExceptionLogger.cs(163,21,163,33): warning CS1591: Missing XML comment for publicly visible type or member 'DatabaseExceptionLogger.LogException(Exception, string)'```

Whereas this one is fine (shows in the dark yellow color):
```
D:\ONOSYS\ONOSYSv4\12\21.RTPConversion\Dev\ONOSYS.Api\Services\DatabaseExceptionLogger.cs(148,30,148,45): warning CS1591: Missing XML comment for publicly visible type or member 'DatabaseExceptionLogger.GetDatabaseName()'```

**Comment by mvandersteen** [comment]
A solution I sue for removing the false positives is below
eg:
Sample "error" highlighted line is in red but is only a warning.
ReviewRepo.cs(131,28): warning CS0168: The variable 'exception' is declared but never used

The following works for me, ie. check if it is NOT preceded with a warning an BC or CS reference number directly after the warning. I'm not sure it if needs cater for any other warning number prefixes (BC or CS etc)

MyRegExPattern[4] beomes:
(\W|^)^(?!.*warning\s(BC|CS)\d+:).*(error|fail|failed|exception)[^\w\.]

This should fix the previous comment from matthewpavkov as well

**Comment by matthewpavkov** [comment]
Thanks @mvandersteen. Hadn't gotten around to doing this yet. That works for me too, as you suspected.
