### ISSUE TITLE
VSColorOutput don't work anymore on Visual Studio 2019 - 16.6.0 Preview 1

### ISSUE THREAD

**Issue by Daddoon** [mike-ward/VSColorOutput#111]
Hi,

Except the fact that the extension is not listed anymore on Visual Studio 2019 16.6.0 Preview 1 (see my report here: https://developercommunity.visualstudio.com/content/problem/954025/some-visual-studio-2019-extensions-are-missing-fro.html ), even by installing it manually from the Marketplace, it does not color the build output.

It was working on previous version.
I don't know if it's a Visual Studio 2019 API breaking change or a bug.

**Comment by mike-ward** [comment]
I generally don't mess with the preview editions. Too many moving parts. I'm using the recently released 16.6.0 release without issue.

**Comment by Daddoon** [comment]
Thanks for the feedback.

I'm mainly using the Preview versions of Visual Studio 2019 because i'm often working with Blazor, and actually, new releases are often only supported on the Preview version (but i may have to recheck).

Do you want that i submit a bug report about this behavio on the Visual Studio Developer bug tracking ?

**Comment by mike-ward** [comment]
Can't hurt to put it on their radar. They have made efforts in the past to keep VSColorOutput humming along.

**Comment by Daddoon** [comment]
Thanks Mike.

Just for tracking purpose: https://developercommunity.visualstudio.com/content/problem/954080/vscoloroutput-extension-console-colorization-not-w.html

**Comment by Daddoon** [comment]
It seem that Microsoft Visual Studio Team choose to say that they are not concerned about that because it's a third party problem. Pretty disappointed by their lazyness (see updated https://developercommunity.visualstudio.com/content/problem/954080/vscoloroutput-extension-console-colorization-not-w.html).

This mean that someone will have to dig why it doesn't work anymore in current VS2019 versions.
I love Microsoft products and folks at it, but this is a shame.

**Comment by mike-ward** [comment]
That is disappointing. When 16.6 is released I'll have a look. Thanks for notifying me and following up.

**Comment by udlose** [comment]
@mike-ward  @Daddoon 
Here is the reason that it is VSColorOuput isn't working with the newer VS versions:

Per https://developercommunity.visualstudio.com/content/problem/961555/new-find-in-files-expereince-is-not-supported-by-e.html?childToView=970840#comment-970840,

> We usually don't go in implementation details, but we took a look at the extension code on GitHub. The extension unfortunately is not using any standard API for the coloring of text in the find results window (old or new). What its unfortunately doing is trying to see if any window has a summary text starting with

> "Find All, "TermToFind", Entire Solution"

> and then starts applying the colors. Its a sort of a hack :( In the newer version we moved the summary text out of the results view so that when you scroll you always have the summary in view and as a result the extension failed. We are looking at our options here on how to proceed on this and we will update you soon.

**Comment by Daddoon** [comment]
Thanks for the feedback @udlose !

**Comment by udlose** [comment]
BTW, I am using the latest release (non-preview) v16.5.2 and the issue is present there as well.

**Comment by mike-ward** [comment]
Odd, 16.5.2 working here. I would definitely be hearing from others if it failed in 16.5.2 in general.

**Comment by udlose** [comment]
Here is the new ListView:
![image](https://user-images.githubusercontent.com/656118/78192470-d7c41380-743d-11ea-8a00-ba96ad1dc21b.png)

Here is the default "Find in Files" view:
![image](https://user-images.githubusercontent.com/656118/78192567-02ae6780-743e-11ea-8ef3-8d6f5dfaee28.png)

**Comment by mike-ward** [comment]
@udlose Is the build output displaying colors in 16.5.2?

**Comment by udlose** [comment]
> @udlose Is the build output displaying colors in 16.5.2?

@mike-ward No, it's not.  It's not displaying colors in either ListView or default "Find in Files" view.  Please my screenshots above in my reply from yesterday.

**Comment by mike-ward** [comment]
> No, it's not (what?)

No it's not showing colors in the build output window? I understand it's not working in Find in Files but that's not what I'm asking. Apologies if I'm being dense.

**Comment by udlose** [comment]
I'm sorry - I misread your comment.  I was the one being dense :|

Yes, it is displaying colors correctly in the Output window:
![image](https://user-images.githubusercontent.com/656118/78273330-4c499180-74d4-11ea-89ac-8fd43c266f7b.png)

**Comment by Daddoon** [comment]
Weird it does not appear with color for me.

I would have tested on the latest preview but another bug prevent to see your extension from the gallery within VS2019

**Comment by Daddoon** [comment]
Some good news:

> We are making sure the scenario works by allowing the hack VSColorOutput used for coloring the older find window in the new find results window list view as well, since quite a few users have voted for it :) We are still deciding on which update the fix will be in but will notify you shortly. Sorry for the incorrect diagnosis by my colleauges earlier

https://developercommunity.visualstudio.com/content/problem/954080/vscoloroutput-extension-console-colorization-not-w.html

So you may not have to change your code in the end.

**Comment by udlose** [comment]
@Daddoon I don't think that VS should have to be making changes though.  This is a good example of what happens when you base something on a non-standard way "hack".  IMO. the correct thing to do is to have the extension fixed.  

It's ridiculous that someone would even file a bug with Microsoft for a 3rd party VS Extension; the problem is with the extension - NOT with VisualStudio. That's like telling Google that Chrome is broken if a website doesn't load.

**Comment by mike-ward** [comment]
I'm ok with fixing this on my end. Just need a hint how to proceed. Back in 2011 when I started this project on Codeplex docs were not as good

**Comment by udlose** [comment]
> I'm ok with fixing this on my end. Just need a hint how to proceed. Back in 2011 when I started this project on Codeplex docs were not as good

@mike-ward I totally get it :) I'd suggested in the MS bug thread that the VS Team that was investigating the issue try to coordinate with you on working out a fix - see https://developercommunity.visualstudio.com/comments/977458/view.html

I'd like to believe that they will do so as it looked to me that they implied there was a better way to accomplish what you're trying to do.

**Comment by Daddoon** [comment]
From a deleted comment from Microsoft Team i received, it seem that even with their "fix" it would not be sufficient, as it would not fix the Output window specifically.

Wishing you will find the official way @mike-ward  !
Otherwise, i will try live without this great extension !

**Comment by mike-ward** [comment]
Worse comes to worse I'll remove the find in files code when 16.6 is released.

**Comment by mike-ward** [comment]
So I installed VS Preview 2. VSColorOutput successfully installed and colors build output. No errors logged.

**Comment by Daddoon** [comment]
I installed the same VS2019 version, except it's the Enterprise edition, still not working on my side.

There is actually also a bug that prevent to see your extension (at least from my side) in the VS2019 gallery, so i had to install it manually from the marketplace.

Is VSColorOutput version 2.74 right ?
I tried to enable or disable all option just for testing, still no color.

I don't know why it still works for you. Or maybe we are not using the same Output window for whatever reason, since they made some evolution at Microsoft ?

**Comment by mike-ward** [comment]
Latest release is 2.71. I downloaded it from the gallery. I use the standard output window (View | Output).

As to not seeing it in the gallery, I usually have to update the extension manifest when a new version comes out.  

Could be another extension causing an issue. Once had a crash due in part to Visual Assist Extension. They later fixed their end (awesome people there).

**Comment by Daddoon** [comment]
Oopsies, i have the 2.71 version too, it was a typo error on the numeric pad of my keyboard !
I'm using the same Output window then.

I will try to dig if another extension is causing issue.

**Comment by mbutler-qc** [comment]
I lost custom build output coloring when I was messing around switching to high contrast and back in Windows 10 and ended up fixing it by closing Visual Studio (2019 v16.5.3), deleting the config json file at %AppData%/VSColorOutput/vscoloroutput.json and then restarting Visual Studio.

**Comment by Daddoon** [comment]
> 
> 
> I lost custom build output coloring when I was messing around switching to high contrast and back in Windows 10 and ended up fixing it by closing Visual Studio (2019 v16.5.3), deleting the config json file at %AppData%/VSColorOutput/vscoloroutput.json and then restarting Visual Studio.

This did the trick !
The weird thing is that color disappeared while updating VS2019 Preview originally.

Deleting the file and relaunching VS2019 Preview did the trick, colors are now back ! Thanks for the tips !

**Comment by mike-ward** [comment]
Sounds like maybe the config file was corrupted. I'm going to have to look into making that part more robust.

**Comment by Daddoon** [comment]
May i close the issue ?

**Comment by mbutler-qc** [comment]
> Sounds like maybe the config file was corrupted. I'm going to have to look into making that part more robust.

Here's the file I deleted...
[vscoloroutput.json.txt](https://github.com/mike-ward/VSColorOutput/files/4456596/vscoloroutput.json.txt)

Comparing to the new config file generated it looks like the "Patterns" property had been wiped out. 
![image](https://user-images.githubusercontent.com/7382004/78904639-c2ba3680-7a74-11ea-9f36-0412b7c03825.png)

**Comment by mike-ward** [comment]
Yeah, close it. I've had others ask for a "Reset to Defaults" feature. I'll add a git to do this and deal with the null patterns issue there. Thanks.

**Comment by Daddoon** [comment]
Thanks for all your work :) !
