### ISSUE TITLE
No longer colorizing in VS2019 - Reinstalled, etc.

### ISSUE THREAD

**Issue by NW7US** [mike-ward/VSColorOutput#115]
Sometime, this week, without **VS2019** updated, my **VSColorOutput** colorizing stopped.  I have uninstalled, reinstalled, with restarts in between.  No luck.  **Any ideas?**

![2020-04-30_9-41-23](https://user-images.githubusercontent.com/5557774/80724402-6a9cb000-8ac7-11ea-940c-9082d116dcc1.jpg)

**Comment by mike-ward** [comment]
Try deleting your settings file and restarting VSColorOutput.

 %AppData%/VSColorOutput/vscoloroutput.json

**Comment by NW7US** [comment]
Wonderful!  It is working, once again.  Thank you for the quick response.  That deserves another donation.

**Comment by NW7US** [comment]
Closing.
