### ISSUE TITLE
Regular long hangs in VS2019

### ISSUE THREAD

**Issue by SanderBouwhuis** [mike-ward/VSColorOutput#117]
I started using this extension, and I absolutely love it!

The problem which forced me to uninstall it is that VisualStudio regularly hangs when I use this extension. It will hang for about 5 seconds and then continue. Trying to scroll through a coloured output window hangs Visual Studio completely and then continues. Any scrolling I do will again lead to 5 second hangs.
Is there anything I can do to get this fixed?

**Comment by mike-ward** [comment]
It's possible it is conflicting with another extension. Not sure there is more I can offer.

**Comment by SanderBouwhuis** [comment]
You were right. It seems to have to do with an extension to improve side/horizontal scrolling. I decided to uninstall the other extension because colour output is much more valuable.
Could you add more colours please?
