### ISSUE TITLE
Attach color output to the ASP.NET Core Web Server output

### ISSUE THREAD

**Issue by nCubed** [mike-ward/VSColorOutput#118]
When running a .net core website out of VS 2019, a separate console window provides all output for the web application. Is it possible to use VSColorOutput to colorize the ASP.NET Core Web Server output?

**Comment by sanketkdarji** [comment]
@nCubed I think it's possible, just add custom regex pattern. i.e. (info:) or ((info:).*) for info.

**Comment by nCubed** [comment]
Thanks @sanketkdarji - didn't even know there was an option to add a new pattern. Cheers!
