### ISSUE TITLE
remove useless .net 4.6 requirement

### ISSUE THREAD

**Issue by MagicAndre1981** [mike-ward/VSColorOutput#12]
Version 2 has the useless requirement of .net 4.6. 

I've downloaded the VSColorOutput.vsix, expanded it, changed the SupportedFrameworkRuntimeEdition entry in extension.vsixmanifest back to 4.5, created a new zip and renamed it back to VSColorOutput.vsix and it installs fine and works fine with .net 4.5.2.

So there is no need to have the requirement of .net 4.6.

**Comment by mike-ward** [comment]
For some reason, when I read this an image comes to mind:

![image](https://cloud.githubusercontent.com/assets/567927/12035098/2a1736dc-ae07-11e5-8ec6-15560cd15b56.png)

I think the word you want is "unnecessary", not useless.

Thanks for your feedback and I'll see what I can do.
