### ISSUE TITLE
set foreground/background per display selection and highlight

### ISSUE THREAD

**Issue by PaltryProgrammer** [mike-ward/VSColorOutput#121]
Thank you for the fine extension. May I make a request please. When I select an error message in the build output the red foreground is almost indiscernible from the now darkened background. I would find it very helpful if the foreground/background can be specified upon each: display selection and highlight. Thank You Kindly Best Wishes Cheerios

**Comment by mike-ward** [comment]
I had the same problem. I changed the colors in the Visual Studio Fonts and Colors dialog. You'll need to select the Output Window from the drop down as pictured.

![image](https://user-images.githubusercontent.com/567927/97574431-3a23c900-19b9-11eb-96fe-6577f4e4ee5f.png)
