### ISSUE TITLE
The World of Grey

### ISSUE THREAD

**Issue by DBJDBJ** [mike-ward/VSColorOutput#122]
## I have no colours any more

This is the VS about box

![image](https://user-images.githubusercontent.com/145155/97533698-fa5ce180-19b8-11eb-9f0f-64ee50dc98e0.png)

And this is the situation

![image](https://user-images.githubusercontent.com/145155/97533802-2ed09d80-19b9-11eb-9a1c-4e7ea6c37525.png)

This has started since the "begging message" appeared. There were still colours at that moment. Then as instructed I went into settings. Could not see anything new in the setting pressed OK and went back. Since that moment my world is grey.

This is a pitty, Mike. I can not donate now. Please advise.

**Comment by mike-ward** [comment]
In my experience, this has (almost) always been the result of some collision with other extensions. I'm also running 16..7.7 with lots of other extensions and seeing no issues.

![image](https://user-images.githubusercontent.com/567927/97573937-7c003f80-19b8-11eb-82c7-864f0760e191.png)

**Comment by DBJDBJ** [comment]
I have almost no extensions

![image](https://user-images.githubusercontent.com/145155/97915977-a48a8f80-1d52-11eb-8f7d-920a244d2307.png)

of which only one is not official and can be removed ... but that one is also of Microsoft origin ...

When I remove your extension are all the setups removed too?

**Comment by 0x0309** [comment]
I've seen this too and whenever this happens it's because the regex array in the json config file has been overwritten to ``null``. Everything else in the config is unchanged though. I have no idea what causes it, just happens randomly maybe once every 2 or 3 weeks.
You could delete the config and it will get re-created I think. I've checked mine into git so can just revert it when this happens but would be good if it the config didn't break in the first place.

**Comment by DBJDBJ** [comment]
@0x0309  Lovely jubbly, but where is the said "JSON config file"?

**Comment by 0x0309** [comment]
The path is ``%APPDATA%\Roaming\VSColorOutput\vscoloroutput.json``

**Comment by mike-ward** [comment]
Only a guess but maybe there's some race condition on startup where the save to file logic is triggered before settings are loaded. I'll add something to not permit saving to file when no regex's are detected.

**Comment by DBJDBJ** [comment]
- Uninstalled. 
- Before removing `%APPDATA%\VSColorOutput.` Looked into `vscoloroutput.json`, there was no `RegEx` array at all.
- Removed `%APPDATA%\VSColorOutput`. 
- Installed. 
- Colours are back.

Thank you all
