### ISSUE TITLE
Use Mock.VerifyAll()

### ISSUE THREAD

**Issue by jzabroski** [mike-ward/VSColorOutput#124]
Hi @mike-ward 

I found your project through Nick Craver posting about "stop on first build error" and your plug-in being one of the ways people add this behavior after-market.

I was looking at what you do to enable this behavior, and was just separately wondering, Why not reduce the lines of code in these tests by calling `Mock.VerifyAll();`?  On one hand, I could answer my own question, in that I know the behavior of this helper has changed over time and is less stable than calling `VerifyAll()` on individual mock instances, but it sure would reduce the lines of code in the tests.

https://github.com/mike-ward/VSColorOutput/blob/9cb2bb75b31db110143be6e30bd41ca0f8e04e59/VSColorOutput.Tests/BuildEventsTests.cs#L198-L208

**Comment by mike-ward** [comment]
Gosh, it's been years since I looked at that code. Maybe I didn't understand something about mocks at the time or maybe it just grew that way as I wrote more tests.

**Comment by jzabroski** [comment]
@mike-ward Would you accept a PR to simplify it?

**Comment by mike-ward** [comment]
Of course.
