### ISSUE TITLE
Infinite Recursion

### ISSUE THREAD

**Issue by myCrack** [mike-ward/VSColorOutput#126]
https://github.com/mike-ward/VSColorOutput/blob/a7203a92bf85e30c54c261488f7ba7b60a848964/VSColorOutput/State/Settings.cs#L98-L119

https://github.com/mike-ward/VSColorOutput/blob/a7203a92bf85e30c54c261488f7ba7b60a848964/VSColorOutput/State/Settings.cs#L146-L152

`Settings.GetSettingsFilePath -> Settings.Save -> Settings.GetSettingsFilePath -> ...`

In `GetSettingsFilePath`, If `settingsPath` ditn't exist, then, at line 117 invoked method `Save` on new instance, then again, at line 115 invoked static method `GetSettingsFilePath`.

**Comment by mike-ward** [comment]
Well that's not very smart of me...
