### ISSUE TITLE
Output window is always re-opened and focus when debug starts

### ISSUE THREAD

**Issue by CrendKing** [mike-ward/VSColorOutput#129]
I noticed whenever I start debugging, the output window is always opened and focused. After carefully repairing and dissecting all the VS settings and extensions, I found the cause is the "Show Debug Window on Debug" setting. I probably turned it on without knowing exactly what it does. The text is kinda misleading, since there is no "Debug Window" in VS2019.

I suggest changing this text a bit to match its behavior, and adding "Show and focus" to the description section.

**Comment by mike-ward** [comment]
Thanks for the feedback. The text probably should say something like, "Open debug console output on debug".

**Comment by CrendKing** [comment]
As long as it mentions "output", I think it'd be fine.
