### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [mike-ward/VSColorOutput#131]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by mike-ward** [comment]
It's on my radar. Microsoft has not released details on how to migrate extensions.

**Comment by joesdu** [comment]
mark

**Comment by Everest2020** [comment]
Please check the online documentations :)

https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by mike-ward** [comment]
I've created a new repository for VS 2022.

The release be found at: https://github.com/mike-ward/VSColorOutput64/releases/tag/2021.1

**Comment by joesdu** [comment]
> I've created a new repository for VS 2022.
> 
> The release be found at: https://github.com/mike-ward/VSColorOutput64/releases/tag/v2021.3

thanks for your work

**Comment by Everest2020** [comment]
@mike-ward Many thanks for your efforts.

Btw, want to mention that maybe you can split the project so that it can support both VS2019 and VS2022. please see https://www.youtube.com/watch?v=-PKIPTW6km0
