### ISSUE TITLE
Please consider activating GitHub Sponsors

### ISSUE THREAD

**Issue by Reputeless** [mike-ward/VSColorOutput#138]
I have been using VSColorOutput for a long time. 

https://mike-ward.net/donate/
PayPal does not support donations from Japanese users due to legal issues, so I would like to donate to you through a one-time tier of GitHub Sponsors instead. Please consider activating GitHub Sponsors in your GitHub account. Thank you.

**Comment by mike-ward** [comment]
Interesting. I had no idea GitHub had a sponsor thingy.

**Comment by mike-ward** [comment]
Sponsorship turned on for VSColorOutput64.

**Comment by kiddailey** [comment]
Am I missing something?  I came here to sponsor as well and it doesn't seem to be available.  Any chance it could get re-enabled?

**Comment by mike-ward** [comment]
It says it is enabled. The only funding link enabled is GitHub. Is the sponsorship button visible?

<img width="768" alt="image" src="https://github.com/mike-ward/VSColorOutput/assets/567927/a0051599-fe9e-4216-a50a-f9a94e42e2bc">

**Comment by mike-ward** [comment]
Ah, I see the issue. Sponsorship is enabled for VSColorOutput64. 

https://github.com/mike-ward/VSColorOutput64
