### ISSUE TITLE
VS 2022 color issue

### ISSUE THREAD

**Issue by juaxix** [mike-ward/VSColorOutput#139]
Looks like everything is of the default color when using it in the latest VS2022 (Version 17.2.0 Preview 1.0)
![image](https://user-images.githubusercontent.com/996806/154809480-9c68f9bc-e36b-4668-b1c0-7c5234f2ca41.png)

**Comment by jeeshenlee** [comment]
Not sure if I'm right, I notice there are no default values for the Classifier Pattern (Regex)

**Comment by PiterGoCompany** [comment]
As @mike-ward  mentioned on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput&ssr=false#qna), try to remove settings file at %AppData%/VSColorOutput/vscoloroutput.json or settings file at %AppData%/VSColorOutput64/vscoloroutput.json.

**Comment by mike-ward** [comment]
I agree. It looks like the settings file got nuked.

**Comment by juaxix** [comment]
That worked :) 
![image](https://user-images.githubusercontent.com/996806/167274988-9429db8b-ee8f-448f-89de-c1f95c25367b.png)

**Comment by lu230601** [comment]
Awesome, thanks, finally solved my problem
