### ISSUE TITLE
Background colors not configurable

### ISSUE THREAD

**Issue by co24** [mike-ward/VSColorOutput#14]
Previous versions allowed the configuration of background colors via the Fonts and Colors options page of Visual Studio. Beginning with version 2.0, one cannot configure different background colors for the classifications any more. 

This was very convenient, e.g. for using a red background for all lines classified as "Error". It would be gratefully acknowledged if this feature could be reintroduced.

**Comment by mike-ward** [comment]
That was a breaking change and one of the reasons I bumped to version 2 (Semantic versioning). Moving the colors to a separate dialog makes the program easier to configure. V2 also uses a transparent background so it plays better with theme changes. I'm sorry for inconvience.
