### ISSUE TITLE
warnings and messages turn red

### ISSUE THREAD

**Issue by PaltryProgrammer** [mike-ward/VSColorOutput#142]
Greetings Kind Regards Thank You for providing VSColorOutput I hope you enjoyed the cup of coffee. Please see attached PNG demonstrate warnings and messages turn red. Thank You Kindly

![turning red ](https://user-images.githubusercontent.com/48535920/200154183-21d2ce9b-fb6a-4f14-930f-4aa811f61256.png)

**Comment by mike-ward** [comment]
You can always edit classifier patterns to suit your needs.

**Comment by PaltryProgrammer** [comment]
Please note the color setting as can be seen in the dialog box for Warnings and Messages are not Red however some but not all are Red colored in the Build output window.
