### ISSUE TITLE
output window all gray

### ISSUE THREAD

**Issue by IngmarBitter** [mike-ward/VSColorOutput#145]
I recently got a new PC and installed everything fresh from latest installers, incl. Visual Studio 2022 Enterprise and VsColorOutput through the VS Extension manager.  Now all text in the output window is gray. What do I do to get the color coding to work?
... when I edit the VsColorOutput64 options field "Build Text" from the default gray to white, then the output text does indeed become white. But when I edit the field "Build Message" nothing changes in the output window.

**Comment by myCrack** [comment]
@IngmarBitter, It seems that the right repository for the issue is [vscoloroutput64](https://github.com/mike-ward/VSColorOutput64/issues/new).

**Comment by myCrack** [comment]
Here is the same issue https://github.com/mike-ward/VSColorOutput/issues/139

**Comment by IngmarBitter** [comment]
is indeed the same as #139 and the same fix worked for me:
just delete  %AppData%/VSColorOutput64/vscoloroutput.json
