### ISSUE TITLE
Extension doesn't work properly

### ISSUE THREAD

**Issue by JD1609** [mike-ward/VSColorOutput#147]
When I start build so all messages are gray.. It doesn't matter if it's a warning or a bug, just all is gray :( Any ideas?

my output
![image](https://github.com/mike-ward/VSColorOutput/assets/74508566/7bd3bdcc-5f96-4c30-aab4-b8c5f464e41a)

my settings:
![image](https://github.com/mike-ward/VSColorOutput/assets/74508566/940e48de-a169-4db1-a480-dd9e941ae73c)

**Comment by JD1609** [comment]
Ok, so problem was that I hadn't filled out the Regex expression

**Comment by mike-ward** [comment]
If you delete the settings file you will get the default patterns.
