### ISSUE TITLE
[Bug] Per solution config is not overriding the AppData config

### ISSUE THREAD

**Issue by t4m45** [mike-ward/VSColorOutput#148]
VS 2019 & VSColorOutput v2.73

I've copied the vscoloroutput.json file into the directory where my .sln file is located and added it to the solution, then I modified the following regex from this:

    {
      "ClassificationType": 2,
      "IgnoreCase": true,
      "RegExPattern": "(\\W|^)^(?!.*warning\\s(BC|CS|CA)\\d+:).*((?<!\/)error|fail|failed|exception)[^\\w\\.\\-\\+]"
    },

To this:

    {
      "ClassificationType": 2,
      "IgnoreCase": true,
      "RegExPattern": "(\\W|^)^(?!.*warning\\s(BC|CS|CA)\\d+:).*((?<!\/)error|fail|failed|(?<!custom\\.)exception)[^\\w\\.\\-\\+]"
    },

So it should ignore the word 'exception' if it starts with "custom." like "custom.exception".
This change is not respected by the extension (even after VS restart), until I change the regex in to config file that is located in the AppData directory and restart the visual studio.

**Comment by mike-ward** [comment]
VSColorOutput64 is the currently supported project. VSColorOutput is for legacy systems. Furthermore, I don't have  a windows machine at the moment. The issue likely lies in `settings.cs`. If you're up for it, submit a fix and I'll publish an update because VSColorOutput64 will not work with VS2019.

**Comment by t4m45** [comment]
I've subbmitted pull request #149 
This was my first fork and pull request ever on this platform, I hope I created them properly.

**Comment by t4m45** [comment]
Hello Mike,
Can you publish the update this week?

**Comment by mike-ward** [comment]
Preliminary release setup. Need a couple of you to test and verify. 

https://github.com/mike-ward/VSColorOutput/releases/download/untagged-59d0e79d882d259164ef/VSColorOutput.vsix

**Comment by t4m45** [comment]
The link is broken.

**Comment by mike-ward** [comment]
Can you see the draft release (2.74) in the release page?

**Comment by mike-ward** [comment]
Looks like draft releases are not visible. I published the release at https://github.com/mike-ward/VSColorOutput/releases/tag/v2.74

**Comment by t4m45** [comment]
Tested it with my co-workers and it works perfectly in VS 2019.

Keep in mind, if you are using the default config file (from AppData) and you add a new config file to the solution, you will need to restart visual studio, or open the extensions configuration via `Tools -> Options -> VSColorOutput` and then press "OK", so the settings will be reloaded from the solution's config file.

**Comment by mike-ward** [comment]
Awesome. I'll post it to the marketplace today. Thanks for your help.

**Comment by mike-ward** [comment]
published fix in v2.74 to marketplace
