### ISSUE TITLE
Edit Patterns Not Available under VS2015 UP1

### ISSUE THREAD

**Issue by CheetahChrome** [mike-ward/VSColorOutput#16]
Installed the package and it runs and works on VS2015 UP1. The documentation on page [VSColorOutput](https://visualstudiogallery.msdn.microsoft.com/f4d9c2b5-d6d7-4543-a7a5-2d7ebabc2496) section `Creating Patterns` states 
>The Tools|Options|VSColorOutput|Patterns dialog contains settings. You can add, delete or edit the patterns.

And the description shows a dialog box to edit it.

Yet there is no `Patterns` sub dialog selection tab to VSColorOutput,(only `General`) nor does there appear to be a way to bring up the edit dialog.

**Comment by mike-ward** [comment]
Try clicking the the RegEx Patterns. You'll see a `...` button. Click it.

![image](https://cloud.githubusercontent.com/assets/567927/12222723/a5d411ca-b792-11e5-984b-1dcaa89da75d.png)

**Comment by CheetahChrome** [comment]
Uggg my bad, yep it shows up. Hence not a bug, but now a suggestion to update the docs or make the `...` button visible at all times. Thanks!

**Comment by mike-ward** [comment]
Is there a way to do that in a property sheet?
