### ISSUE TITLE
VS2015 options missing

### ISSUE THREAD

**Issue by mgwalm** [mike-ward/VSColorOutput#2]
I cant find the colour options, eg, LogCustom1 in tools options in VS2015?

the default colour for warnings makes it almost unreadable.

**Comment by kenwarner** [comment]
I have the same problem, even after uninstalling/reinstalling the extension. If I get a chance I'll try to help track it down

**Comment by mike-ward** [comment]
Moved colors in beta 1 to VSColorOutput options window.
