### ISSUE TITLE
VS2010 Professional SP1 crashes compiling project when VSColorOutput is enabled

### ISSUE THREAD

**Issue by IgorT75** [mike-ward/VSColorOutput#21]
It started to happen after recent VSColorOutput update.
VS crashes compiling C++ project when I do Rebuild.
System.NullReferenceException  - see attached log entry.

[VSColorOuputCrash.txt](https://github.com/mike-ward/VSColorOutput/files/128730/VSColorOuputCrash.txt)

**Comment by mike-ward** [comment]
This is a crash in an editor extension. VSColorOutput is not an editor extension. Are you using another extension like Visual Assist? Others have found a conflict with this extension.

**Comment by IgorT75** [comment]
Yes, I do use VA. I'll disable it and try to compile again.

**Comment by mike-ward** [comment]
So does this mean you'll upgrade you review on the extensions site :)

**Comment by IgorT75** [comment]
I upgraded rating.
