### ISSUE TITLE
Don't highlight output stating no errors/warnings

### ISSUE THREAD

**Issue by drewnoakes** [mike-ward/VSColorOutput#22]
I'm building the new xproj/dnx project type and seeing output like this:

![image](https://cloud.githubusercontent.com/assets/350947/13029709/730e81f8-d28b-11e5-87b5-0374a28da81e.png)

This seems similar to issue #3. Perhaps the output format is slightly different in this case.

Each time the magenta/red flashes up, I have cause to pause. It'd be nicer to only see red for real errors.

Thanks for a great VS extension.

**Comment by mike-ward** [comment]
Just change the regular expressions in the settings to suit your needs. There's no way to match every situation.

**Comment by drewnoakes** [comment]
Got this working like so:

![image](https://cloud.githubusercontent.com/assets/350947/13382716/63774eb6-de73-11e5-8cc6-2490bda508b4.png)

You may wish to make this part of the default set though. This is not some exotic project type -- it's set to become the default project type in future.

**Comment by mike-ward** [comment]
I'll add it in a future version. Thanks.
