### ISSUE TITLE
False error: Task "Error" skipped, due to false condition; ...

### ISSUE THREAD

**Issue by onovotny** [mike-ward/VSColorOutput#23]
Would be great if the RegEx/pattern match for error could exclude `Task "Error" skipped` as that shows up in detailed build logs quite a bit.

**Comment by mike-ward** [comment]
You can add your own regex expressions.

**Comment by Banner-Keith** [comment]
This will work. 
(\W|^)^(?!(.*warning\s(BC|CS)\d+:)|(.*?skipped, due to false condition.*)).*(error|fail|failed|exception)[^\w\.]
@mike-ward. Would you consider having this be the default? It covers all of the conditions that are currently covered, and avoids this very common problem.

**Comment by mike-ward** [comment]
Thanks, I'll add it. Regex is one of those black arts I've avoided.

**Comment by Banner-Keith** [comment]
@mike-ward Can't say I blame you. That one took quite a while and a lot of testing to validate. If you need any samples of text that I used to validate this please let me know. Thanks for all your hard work.

**Comment by JeffreyVest** [comment]
@Banner-Keith I tried your regex. Unfortunately for me I still see it greyed out for:

6>C:\src\Trunk\SiteZeus\packages\Microsoft.TypeScript.MSBuild.2.5.3\tools\Microsoft.TypeScript.targets(206,7): error MSB4064: The "ComputeOutputOnly" parameter is not supported by the "VsTsc" task. Verify the parameter exists on the task, and it is a settable public instance property.

**Comment by Banner-Keith** [comment]
@JeffreyVest Was that error grayed out with the original RegEx that VSColorOutput came with or just with the new RegEx I suggested?
