### ISSUE TITLE
false red line marking with VS2012 linker in verbose mode and VSColorOutput 2.2.4

### ISSUE THREAD

**Issue by AlexanderStohr** [mike-ward/VSColorOutput#26]
The middle line is red in my outputs. I was using verbose mode of the linking.

1>        Found "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)
1>          Referenced in bintoopencvconversion.obj
1>          Referenced in lkdemo.obj
1>          Loaded opencv_core310d.lib(opencv_core310d.dll)
**1>        Found "void __cdecl cv::error(int,class cv::String const &,char const *,char const *,int)" (?error@cv@@YAXHAEBVString@1@PEBD1H@Z)**
1>          Referenced in bintoopencvconversion.obj
1>          Referenced in lkdemo.obj
1>          Loaded opencv_core310d.lib(opencv_core310d.dll)
1>        Found "public: static class cv::MatExpr __cdecl cv::Mat::zeros(int,int,int)" (?zeros@Mat@cv@@SA?AVMatExpr@2@HHH@Z)

**Comment by mike-ward** [comment]
False positives are inevitable given that the word error is often used in places where there is no error. You can add a custom rule to suppress this.

**Comment by AlexanderStohr** [comment]
a higher priority rule (of classification type BuildText) for this set of items probably would be:
`^Found \"`
(i have to admit this not yet tested by me. but others might benefit a bit from that line if ever someone visits that issue again.)
