### ISSUE TITLE
warning on "possible error" is red

### ISSUE THREAD

**Issue by AlexanderStohr** [mike-ward/VSColorOutput#27]
this line is marked red for me - it should not be red:

..\..\src\COMMON\fileHelpers.cpp(81): warning C4554: '&' : check operator precedence for possible error; use parentheses to clarify precedence

**Comment by mike-ward** [comment]
Given the variety of warnings and errors, false positives are inevitable. Add a custom rule to suppress this.

**Comment by AlexanderStohr** [comment]
the default action list of VSColorOutput pattern is looking for keywords like error/warning/information plus sometimes some context. this would trigger error-level highlighting even for lines with phrases like "no error".
for improving in my case i ended up creating higher priority entries for the typical MSVC error reporting styles that are rather unique compared to a pure word search. example snippet:
`): warning C`
this ended me up in a (seemingly to work) pattern like this:
`\)\: warning C`
