### ISSUE TITLE
Different target frameworks in projects and packages

### ISSUE THREAD

**Issue by mac2000** [mike-ward/VSColorOutput#29]
Hello, while playing with VSColorOutput I have noticed that there is `targetFramework="net46"` in packages.conf but in csproj files there is `<TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>`

That can be fixed pretty easy the only thing you should decide framework to stick with.

The reason why I am asking abouth that change is because after clongin and compiling project - whole packages.conf files and cproj files are changed and messing things up, so it is hard to decide what should be commited and what not.

**Comment by mac2000** [comment]
@mike-ward will it be ok to commit net452? or you wish to stick with net46?

**Comment by mike-ward** [comment]
It needs to be 4.5.2. I got nothing but grief from trolls about moving to 4.6. Guess upgrading .NET was more than they could handle.
