### ISSUE TITLE
0 error(s) displayed in red

### ISSUE THREAD

**Issue by DavidDeSloovere** [mike-ward/VSColorOutput#3]
Something like this line is displayed in the error color, but it should actually be green:

    Code Analysis Complete -- 0 error(s), 0 warning(s)

**Comment by stinos** [comment]
Does anyone know the proper regex which fixes cases like this? Also msbuild text like {The previous error was converted to a warning because the task was called with ContinueOnError=true.} gets colored in red.

**Comment by DavidDeSloovere** [comment]
I know it might look like a dirty trick, but I'll get it done: a white list of safe messages baked right into the extension. 

"Code Analysis Complete -- 0 error(s), 0 warning(s)" 
"The previous error was converted to a warning because the task was called with ContinueOnError=true."
....

**Comment by stinos** [comment]
I don't think the whitelist is very dirty, after all it's easier than having regexes which are totally unreadable because of all the exceptions which need to be added. Like I just noticed a project I'm working on has a file ```warning.c``` :]

**Comment by mike-ward** [comment]
Just released beta 1. I'll look to add this before the final release.

**Comment by mike-ward** [comment]
I'll add an additional pattern. For now you can add it yourself. I used.

![image](https://cloud.githubusercontent.com/assets/567927/11959527/d1174b82-a89b-11e5-8085-fe0b0ab6d431.png)

**Comment by mike-ward** [comment]
Beta 4 out. Give 'er a spin.

https://github.com/mike-ward/VSColorOutput/releases

**Comment by stinos** [comment]
Tested on VS2013 and all is fine, thanks!

**Comment by DavidDeSloovere** [comment]
Somewhat late, but I can also confirm it works. Thanks.
