### ISSUE TITLE
Nunit Test Adapter

### ISSUE THREAD

**Issue by mac2000** [mike-ward/VSColorOutput#30]
Will be nice to add [NunitTestAdapter](https://www.nuget.org/packages/NUnitTestAdapter/) to Tests project, so build in VisualStudio test explorer will be able to run tests, without need to have NCrunch installed.

Will create pull request for that right after resolving #29

**Comment by mike-ward** [comment]
MS test should work.

**Comment by mac2000** [comment]
It does not see tests (empty list) until you: install some kind of extensions like NCrunch/dotCover/NunitTestAdapter for people who do not use nunit it may be a case to investigate

In any case, if you wish not to include that its ok and issue may be closed, after all appveyor will do the work

**Comment by mike-ward** [comment]
Hadn't noticed it would not see the tests. Go ahead and add it.
