### ISSUE TITLE
web page depiction for pattern panel can be improved

### ISSUE THREAD

**Issue by AlexanderStohr** [mike-ward/VSColorOutput#35]
"The Tools|Options|VSColorOutput|Patterns dialog contains settings."

Its more helpful if the path to the item is described like this:

"The 'RegExClassification Collection Editor' dialog contains the classification pattern settings. It can be opened via 'Tools|Options|VSColorOutput|General|RegEx Patterns [...]'."

**Comment by mike-ward** [comment]
fixed in gallery and web page.
