### ISSUE TITLE
Donation banner take whole output window on small screen

### ISSUE THREAD

**Issue by mac2000** [mike-ward/VSColorOutput#39]
At moment, I'm on small laptop, the only thing I see in output windows is donation banner, actual build result is out of window and I need to scroll each time :(

May be you can make it few lines less (without ASCII graphics) or duplicate build result after it

**Comment by mike-ward** [comment]
The donation banner can be turned off in the settings dialog. Would that fix the issue?

**Comment by mac2000** [comment]
Oh, I'm so sorry, I did not check options at all.

Yep, that is totally fine, thank you for your work!
