### ISSUE TITLE
Dark theme broken background color is used

### ISSUE THREAD

**Issue by dotnetwise** [mike-ward/VSColorOutput#4]
When using the dark theme, the background of the output window seems to be broken.
It uses the editor background color instead of the Output Window Plain Text Background.

See below.

![image](https://cloud.githubusercontent.com/assets/485535/5662632/7ee9ddfc-9744-11e4-832e-720d447a14f7.png)

**Comment by mike-ward** [comment]
See http://mike-ward.net/2014/12/11/vscoloroutput-for-visual-studio-2015/

**Comment by mike-ward** [comment]
Prove me wrong. Clone the code and fix it.

**Comment by evakili** [comment]
I have the same problem but I use this method as a workaround:
As in above screenshot @dotnetwise said, you can see that the back color of output window and text editor are different. So if you simply set back color for output window plain text same as back color of text editor plain text, the problem will be dissappeard.
It seems that the root of this problem is in #5.

**Comment by xavier-rigau** [comment]
Hi Mike,

First off, thanks for creating this and making it available to everyone. It's been really helpful for me in spotting that one line out of several hundred in my log output.

I tried switching back and forth between Light and Dark themes and restarting, but no joy. What finally did work for me was similar to evakili's post:

Tools --> Options --> Environment --> Fonts and Colors

Show settings for:Output Window

Set Item background to Black (not Default or Automatic) - that caused VSColorOutput's output background to switch immediately. Could it be that selecting "Default" or "Automatic" doesn't generate the color change notification you're referring to?

Anyway, problem solved for me. Thanks again.

**Comment by dotnetwise** [comment]
Thanks for sharing this fix! It works amazingly well!

**Comment by amaechler** [comment]
Mike's workaround did it for me.

**Comment by NickNightingale** [comment]
Workaround good for me too in 2015RC. It was already working correctly in 2013.

**Comment by jklaus** [comment]
Any word on whether or not M$ will be resolving this issue?

**Comment by enkafan** [comment]
this work around fixed it for me too. Seems to have fixed a similiar problem with NCrunch forgetting it was in dark mode too. 

I actually regret not sending a Frown to MS with a screenshot. Per @davkean this is a good way to get things prioritized for later fixes in Visual Studio

**Comment by IwishIcanFLighT** [comment]
@xavier-rigau's workaround worked fine for me (VS2015). Thanks a bunch!

**Comment by oatsoda** [comment]
@mike-ward fix by changing the themes worked for me.  I was on the Dark theme and the "Default" background colour for the Output Window was showing as silvery-grey rather than the dark gray(black).  Changed themes and a bit of VS restarting and the "Default" background colour for the Output Window returned to be the dark gray/black as you would expect.

**Comment by jakubsuchybio** [comment]
![image](https://cloud.githubusercontent.com/assets/6567287/11610965/eb76e336-9bb5-11e5-933b-94ae4d014399.png)
Tried everything you suggested guys, but nothing solved this... 
I am using dark theme. 
I tried to change Fonts and Colors -> Output window -> Plain Text -> Item Background to black and it changed the background elsewere in output window, but NOT Item Background, which is same as on picture above.
I tried to change Fonts and Colors -> Text Editor -> VSOutputColor -> Everything -> Item Background to black and it didn't do anything.

**Comment by mike-ward** [comment]
Did you close and open Visual Studio after making the changes. I have the same issue when I switch themes until I restart Visual Studio. As mentioned before, the notification that tells VSColorOutput that colors have changed is broken. My output looks like your's before restarting. Afterwards,

![image](https://cloud.githubusercontent.com/assets/567927/11613672/2cd6d3ea-9bf7-11e5-8dc9-15015b1de0d9.png)

**Comment by jakubsuchybio** [comment]
Oh yeah. That works. Thanks!

**Comment by mike-ward** [comment]
Should be fixed in beta 1

**Comment by lackovic** [comment]
xavier-rigau solution fixed the problem for me, thanks a lot! In my case I simply went to Tools > Options > Environment > Fonts and Colors > Show settings for: Output Window and pressed the "Use Defaults" button.

**Comment by mike-ward** [comment]
For the record, the newest versions no longer touch the background color so theme switching should no longer be an issue.
