### ISSUE TITLE
Not handle some errors by default

### ISSUE THREAD

**Issue by lobster2012-user** [mike-ward/VSColorOutput#41]
Example

**Errors in** C:\Users\user\Documents\Visual Studio 2015\Projects\speech\postgre.test\postgre.test.xproj
    Package Wheatech.EmitMapper 1.0.0-beta is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Wheatech.EmitMapper 1.0.0-beta supports: net461 (.NETFramework,Version=v4.6.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

(i added few regex conditions)

**Comment by mike-ward** [comment]
The next release will have new patterns to account for the change in format of error messages in .NET Core

**Comment by lobster2012-user** [comment]
1.
May be you add uploading of default regex templates by extension from your site?
You can update this list without updating of extension.

2.Another problem
Can you add another format of timestamp (HH:mm:ss) ?
Thanks.
