### ISSUE TITLE
Visual Studio 2017 Support

### ISSUE THREAD

**Issue by vincentw56** [mike-ward/VSColorOutput#44]
Any chance of support for VS 2017?

**Comment by mike-ward** [comment]
The vs15 branch is for vs 2017. Haven't released it yet because VS hasn't released. Yes I know there's an RC but I've been burned before releasing before the final.

**Comment by vip32** [comment]
+1

**Comment by cristianmad** [comment]
+1

**Comment by MoaidHathot** [comment]
+1

**Comment by schuettecarsten** [comment]
According to Microsoft, VS2017RC is "production ready".

**Comment by mike-ward** [comment]
Sorry, but once bitten, twice shy.

If you like, you can build/install the vs15 branch which is VS 2017 ready.

**Comment by schuettecarsten** [comment]
Compiled it myself. Works as expected.

**Comment by mike-ward** [comment]
For those interested. I published a prerelease

https://github.com/mike-ward/VSColorOutput/releases/tag/v2.5

**Comment by vip32** [comment]
v2.5 works great with latest vs2017rc!

**Comment by Ziriax** [comment]
This is strange, I installed it on two PCs with VS 2017 RC4, one works fine, but the other doesn't, VSColorOutput is even not listed as an extension. But reinstalling says it is already installed.

**Comment by vip32** [comment]
I unstalled the extension, suddenly hat frequent vs2017 lockups. Not sure if it was related, have to test again as rc4 is now stable.

**Comment by Ziriax** [comment]
Personally I have the impression that RC4 is less stable than RC3... Not sure if it is related to any extension

**Comment by vip32** [comment]
True, but the lockup occurred with rc3. Anyway march 7th wil bring us rtm
,☺️
