### ISSUE TITLE
Show Time Stamps False breaks the same functionality of the Productivity Power Tools

### ISSUE THREAD

**Issue by gigios** [mike-ward/VSColorOutput#47]
I have installed on my VS2017 RTM the extension "Visual Studio Productivity Power Tools" where there is the similar functionality ("Time Stamp Margin").
The problem is that I want to use the VS-PPT functionality (because more 'compact') instead the VSColorOutput way.
To do this I have disabled (set to false) the "Shot Time Stamps" property in the option panel.
The problem is that in this way also the VS-PPT does not works.
If I disable the extension VSColorOutput, the VS-PPT works again.

(PS: Suggestion for the Time Stamps, add a property to define the 'format' to use in the time shown in the output window, in this way should be possible to customize the visualization)

**Comment by mike-ward** [comment]
Sounds to me like it's a bug in VSPPT. See issue #19 for a similar issue with another popular extension.

**Comment by gigios** [comment]
I have posted the same issue also on the VS-PPT but for the moment I don't have received an answer.
[VS-PPT Issue #97](https://github.com/Microsoft/VS-PPT/issues/97#issuecomment-285607816)

**Comment by 0x084E** [comment]
> (PS: Suggestion for the Time Stamps, add a property to define the 'format' to use in the time shown in the output window, in this way should be possible to customize the visualization)

This would be a really nice addition since the time stamp format is the only thing which makes me use the PPT time stamp extension.

**Comment by mike-ward** [comment]
Scheduled for 2.7
