### ISSUE TITLE
No settings in options window

### ISSUE THREAD

**Issue by MacTwist** [mike-ward/VSColorOutput#49]
The extension works fine, in fact I wanted to turn off the message at the bottom of the build window and started looking for the settings. Unless I'm not looking at the right spot, it is nowhere to be seen. 

![image](https://cloud.githubusercontent.com/assets/26745110/24413992/19f00fe4-13ab-11e7-98b3-79d0ca04b4ef.png)

**Comment by mike-ward** [comment]
Um... that's a first (in 8+ years). Obviously something different about the environment. Likely a conflict with another extension. You can edit the settings file directly in `%AppData%/VSColorOutput/Roaming/vscoloroutput.json`

**Comment by NworbLegin** [comment]
I am also having this issue with VS2015 as I can not see the options entry. I have various extensions installed including Nsight Tegra and Visual Assist.

**Comment by rubtk** [comment]
Same problem with VS2012! And i have not found vscoloroutput.json!

**Comment by mike-ward** [comment]
If you roll back to the previous release does it work?

**Comment by rubtk** [comment]
Where to find previous one?

**Comment by mike-ward** [comment]
Click the releases link at the top of the repository.

**Comment by rubtk** [comment]
Switched back to previus version, now it works!

**Comment by mike-ward** [comment]
The only thing that changed b/t the two versions was the manifest. That was needed to comply with VS 2017. Price of progress I suppose.

**Comment by gcaplan** [comment]
Still an issue in VS 2019.

**Comment by anders43** [comment]
Seems after I uninstall "Color Picker" the setup dialog appears again under Options/VSColorOutput.
