### ISSUE TITLE
VSColorOutput settings should not be in TextEditor but in OutputWindow

### ISSUE THREAD

**Issue by dotnetwise** [mike-ward/VSColorOutput#5]
They should be in the `Output Window` instead.
Since they are all affecting the Output Window anyways.

![wrong](https://cloud.githubusercontent.com/assets/485535/5662962/cfec648c-9748-11e4-8b58-b28444432f9d.png)

![correct](https://cloud.githubusercontent.com/assets/485535/5662958/b99d4912-9748-11e4-8c51-b2f46e86b0b0.png)

**Comment by mike-ward** [comment]
At the time I wrote this, VS did no allow adding colors to the output windows settings. Haven't checked in a while but nothing leads me to believe that has changed.

**Comment by mike-ward** [comment]
I don't have the time or interest frankly. VS extension development is too
painful and time-consuming. I wrote this extension to solve an issue I was
having. I thought it might be useful to others. It's open source so you're
welcome to send pull requests.

**Comment by NN---** [comment]
+1

**Comment by mike-ward** [comment]
Moved color settings in beta 1
