### ISSUE TITLE
VSColorOutput Stopped working after Recent Update

### ISSUE THREAD

**Issue by c4tachan** [mike-ward/VSColorOutput#50]
I'm running VS 2012. Last week, my VSColorOutput was working perfectly (I'm in love with the extension because of how useful it is). I recieved a notice from Visual Studio that there was an update so I went ahead and downloaded the new package.

Now I'm unable to get the color output to work at all. Plus the additional features like the Elapsed Time and time stamps don't appear to be working either.

I've had other issues with my Visual Studio installation (VS crashes if I try to do anything before it finishes loading a project) so there may be an issue on my end, but if I can get some help figuring out if that is the case I would appreciate it. I really miss my colors.

I've attached a screenshot below.

In the past, the build messages would all be green, and errors would be red. Now everything appears to be white.

![vscoloroutputnotworking](https://cloud.githubusercontent.com/assets/2130211/24623111/5e6c4088-1875-11e7-8778-28ee9088a21c.png)

**Comment by ashuura** [comment]
Same for me, I'm also running VS 2012 and everything in my output stays white since the latest update (2.5).

I've tried deleting the vscoloroutput.json, disabling Visual Assist and disabling Productivity Power Tools but not change so it doesn't look like an external interference.

**Comment by mike-ward** [comment]
If you roll back to the previous release, does it work?

**Comment by ashuura** [comment]
Just tried the 2.4: it works, the colors are back.

**Comment by axeh** [comment]
I can just confirm that 2.5 doesn˛t work on VS2012, but 2.4 works.

**Comment by mike-ward** [comment]
Price of progress I suppose. The new manifest appears to not play nicely with older versions and newer versions require it. I'm not interested in maintaining two releases going forward. I'll publish a new version with a manifest that only supports VS 2017. That should keep the older VS platforms safe from future updates.

**Comment by gekakud** [comment]
Same for me :(
VS2012
