### ISSUE TITLE
Not listed in the Tools|Options dialog (VS2015)

### ISSUE THREAD

**Issue by bdr00** [mike-ward/VSColorOutput#53]
The extension works when I build my project, but its not listed in the tools | options dialog in VS. 

VSColorOutput version:
> 2.5

VS version:
> Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.7.02046

**Comment by akamud** [comment]
Same problem here, using VS 2015

**Comment by akamud** [comment]
Answered here: https://github.com/mike-ward/VSColorOutput/issues/49

**Comment by OlekRia** [comment]
Go to C:\Users\<I.am.a.god>\AppData\Roaming\VSColorOutput
Find there vscoloroutput.json. Change SuppressDonation to true.
Restart VS2017.
Cheers!
