### ISSUE TITLE
Works perfect but does not stay enabled

### ISSUE THREAD

**Issue by GupTk** [mike-ward/VSColorOutput#55]
I am using 2.5 with Visual Studio 2015 Update 3.
The problem the Add-In does not stay enabled.

When I reenable it under Add-In Settings I have to restart Visual Studio. Then I get nice colored output until I restart Visual Studio again.

Any ideas?

I have Windows 7 and UAC disabled.

Thanks

**Comment by mike-ward** [comment]
Does this happen with the 2.4 release? 

https://github.com/mike-ward/VSColorOutput/releases/tag/2.4

**Comment by GupTk** [comment]
Mike,
thanks for the fast reply.

Interestingly both 2.4 and 2.5 do not offer to install the extension to VS 2015 when I use the vsix file.
The offer only 2010 and 2012.

I get the impression, that this might be related to the fact, that i have installed VS 2012 **after** 2015.

Do think this might be the reason?

**Comment by mike-ward** [comment]
Yeah, that's an issue I've run into with .vsix as well. You'll have to uninstall the extension everywhere and then install 2.4.

**Comment by GupTk** [comment]
Mike, thanks again.
after the installations troubles (I could not perform the installation succesfully) the extension decided to to stay enabled for the last 5 days.

Very strange but I close this issue for the time being.
