### ISSUE TITLE
Add timestamp format option

### ISSUE THREAD

**Issue by aplocher** [mike-ward/VSColorOutput#58]
I think it would be great to have the ability to specify the exact format of the timestamp.  

As an example of when this is handy, if I have an ultra-wide layout and put my output window to the side, the timestamp takes much of the readable space (e.g. screenshot below).  

In my example, it would be ideal for me to have just the time (no date, no am/pm, maybe no seconds even).

Thanks!

![image](https://user-images.githubusercontent.com/1132447/28256984-264cd42a-6a7c-11e7-8c1f-20d8194eac7d.png)

**Comment by mike-ward** [comment]
Cool idea. I'm away for a month. Will check back then.

**Comment by Crowley1970** [comment]
I second this suggestion. Use the time format for elapsed build time as well. As a default, use the system settings for displaying the time stamps/elapsed build time.

**Comment by mike-ward** [comment]
Implemented.
