### ISSUE TITLE
Find Results Search Term Color is not being applied in VS2013.Update4

### ISSUE THREAD

**Issue by dotnetwise** [mike-ward/VSColorOutput#6]
The `VSColorOutput Find Results Search Term` `Item foreground` color is not being applied

![image](https://cloud.githubusercontent.com/assets/485535/5663251/272406ca-974d-11e4-8178-2b2fd0d1cd86.png)

**Comment by mike-ward** [comment]
See http://mike-ward.net/2014/12/11/vscoloroutput-for-visual-studio-2015/

**Comment by mike-ward** [comment]
Prove me wrong. Clone the code and fix it.

**Comment by CADbloke** [comment]
From the page Mike linked ...
> Change the colors as you want and restart Visual Studio
> If the colors are not what you expect change the theme (If light, go to dark for instance)
> Restart Visual Studio
> Change back to the original theme
> Restart Visual Studio

Worked for me. Fiddly, yes. Mike's Fault - I very-much doubt it. A lot.

**Comment by stinos** [comment]
Same here: Find results color stays what it is

**Comment by davidp57** [comment]
Well, sorry but it's exactly the same here ...
Microsoft Visual Studio Ultimate 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.5.51209

VSColorOutput   1.4.5

**Comment by ThomasDupuis** [comment]
Same probleme here. 

Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 
Microsoft .NET Framework
Version 4.6.00081

Thank you very much if you can fix this, blue isn't super conveniant with the dark skin of VS that I love!

**Comment by mike-ward** [comment]
Should be fixed in beta 1

**Comment by stinos** [comment]
Awesome, thanks!!
