### ISSUE TITLE
Some Azure build/publish events by default are marked as errors

### ISSUE THREAD

**Issue by AlexeiScherbakov** [mike-ward/VSColorOutput#60]
Type Script Compiler:

`C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.2\tsc.exe  --noEmitOnError --listEmittedFiles --locale ru-RU`

And Roslyn (it is huge one line command)

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1701,1702,1705,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;RELEASE;NETCOREAPP1_1 /errorendlocation /preferreduilang:ru-RU /reference:C:\Users\Alexei\.nuget\packages\microsoft.applicationinsights.aspnetcore\2.0.0\lib\netstandard1.6\Microsoft.ApplicationInsights.AspNetCore.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.applicationinsights\2.2.0\lib\netstandard1.5\Microsoft.ApplicationInsights.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.antiforgery\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Antiforgery.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.authorization\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Authorization.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.cors\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Cors.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.cryptography.internal\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Cryptography.Internal.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.dataprotection.abstractions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.DataProtection.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.dataprotection\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.DataProtection.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.diagnostics.abstractions\1.1.2\lib\netstandard1.0\Microsoft.AspNetCore.Diagnostics.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.diagnostics\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Diagnostics.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.hosting.abstractions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Hosting.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.hosting\1.1.2\lib\netstandard1.5\Microsoft.AspNetCore.Hosting.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.hosting.server.abstractions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.html.abstractions\1.1.2\lib\netstandard1.0\Microsoft.AspNetCore.Html.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.http.abstractions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Http.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.http\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Http.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.http.extensions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Http.Extensions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.http.features\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Http.Features.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.httpoverrides\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.HttpOverrides.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.jsonpatch\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.JsonPatch.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.localization\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Localization.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.abstractions\1.1.3\lib\netstandard1.3\Microsoft.AspNetCore.Mvc.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.apiexplorer\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.ApiExplorer.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.core\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.Core.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.cors\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.Cors.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.dataannotations\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.DataAnnotations.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.formatters.json\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.Formatters.Json.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.localization\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.Localization.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.razor\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.Razor.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.razor.host\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.Razor.Host.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.taghelpers\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.TagHelpers.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.mvc.viewfeatures\1.1.3\lib\netstandard1.6\Microsoft.AspNetCore.Mvc.ViewFeatures.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.razor\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Razor.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.razor.runtime\1.1.2\lib\netstandard1.5\Microsoft.AspNetCore.Razor.Runtime.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.responsecaching.abstractions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.routing.abstractions\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Routing.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.routing\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Routing.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.server.iisintegration\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Server.IISIntegration.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.server.kestrel\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Server.Kestrel.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.aspnetcore.webutilities\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.WebUtilities.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.codeanalysis.csharp\1.3.0\lib\netstandard1.3\Microsoft.CodeAnalysis.CSharp.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.codeanalysis.common\1.3.0\lib\netstandard1.3\Microsoft.CodeAnalysis.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.csharp\4.3.0\ref\netstandard1.0\Microsoft.CSharp.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.dotnet.platformabstractions\1.1.2\lib\netstandard1.3\Microsoft.DotNet.PlatformAbstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.caching.abstractions\1.1.2\lib\netstandard1.0\Microsoft.Extensions.Caching.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.caching.memory\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Caching.Memory.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.configuration.abstractions\1.1.2\lib\netstandard1.0\Microsoft.Extensions.Configuration.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.configuration.binder\1.1.2\lib\netstandard1.1\Microsoft.Extensions.Configuration.Binder.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.configuration\1.1.2\lib\netstandard1.1\Microsoft.Extensions.Configuration.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.configuration.environmentvariables\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Configuration.EnvironmentVariables.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.configuration.fileextensions\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Configuration.FileExtensions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.configuration.json\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Configuration.Json.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\1.1.1\lib\netstandard1.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.dependencyinjection\1.1.1\lib\netstandard1.1\Microsoft.Extensions.DependencyInjection.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.dependencymodel\1.1.2\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.diagnosticadapter\1.0.0\lib\netstandard1.1\Microsoft.Extensions.DiagnosticAdapter.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.fileproviders.abstractions\1.1.1\lib\netstandard1.0\Microsoft.Extensions.FileProviders.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.fileproviders.composite\1.1.1\lib\netstandard1.0\Microsoft.Extensions.FileProviders.Composite.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.fileproviders.physical\1.1.1\lib\netstandard1.3\Microsoft.Extensions.FileProviders.Physical.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.filesystemglobbing\1.1.1\lib\netstandard1.3\Microsoft.Extensions.FileSystemGlobbing.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.globalization.cultureinfocache\1.1.2\lib\netstandard1.1\Microsoft.Extensions.Globalization.CultureInfoCache.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.localization.abstractions\1.1.2\lib\netstandard1.0\Microsoft.Extensions.Localization.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.localization\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Localization.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.logging.abstractions\1.1.2\lib\netstandard1.1\Microsoft.Extensions.Logging.Abstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.logging.console\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Logging.Console.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.logging.debug\1.1.2\lib\netstandard1.3\Microsoft.Extensions.Logging.Debug.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.logging\1.1.2\lib\netstandard1.1\Microsoft.Extensions.Logging.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.objectpool\1.1.1\lib\netstandard1.3\Microsoft.Extensions.ObjectPool.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.options.configurationextensions\1.1.2\lib\netstandard1.1\Microsoft.Extensions.Options.ConfigurationExtensions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.options\1.1.2\lib\netstandard1.0\Microsoft.Extensions.Options.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.platformabstractions\1.1.0\lib\netstandard1.3\Microsoft.Extensions.PlatformAbstractions.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.primitives\1.1.1\lib\netstandard1.0\Microsoft.Extensions.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.extensions.webencoders\1.1.2\lib\netstandard1.0\Microsoft.Extensions.WebEncoders.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.net.http.headers\1.1.2\lib\netstandard1.1\Microsoft.Net.Http.Headers.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.visualbasic\10.1.0\ref\netstandard1.1\Microsoft.VisualBasic.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.win32.primitives\4.3.0\ref\netstandard1.3\Microsoft.Win32.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\microsoft.win32.registry\4.3.0\ref\netstandard1.3\Microsoft.Win32.Registry.dll /reference:C:\Users\Alexei\.nuget\packages\newtonsoft.json\9.0.1\lib\netstandard1.0\Newtonsoft.Json.dll /reference:C:\Users\Alexei\.nuget\packages\system.appcontext\4.3.0\ref\netstandard1.6\System.AppContext.dll /reference:C:\Users\Alexei\.nuget\packages\system.buffers\4.3.0\lib\netstandard1.1\System.Buffers.dll /reference:C:\Users\Alexei\.nuget\packages\system.collections.concurrent\4.3.0\ref\netstandard1.3\System.Collections.Concurrent.dll /reference:C:\Users\Alexei\.nuget\packages\system.collections\4.3.0\ref\netstandard1.3\System.Collections.dll /reference:C:\Users\Alexei\.nuget\packages\system.collections.immutable\1.3.0\lib\netstandard1.0\System.Collections.Immutable.dll /reference:C:\Users\Alexei\.nuget\packages\system.collections.nongeneric\4.3.0\ref\netstandard1.3\System.Collections.NonGeneric.dll /reference:C:\Users\Alexei\.nuget\packages\system.componentmodel.annotations\4.3.0\ref\netstandard1.4\System.ComponentModel.Annotations.dll /reference:C:\Users\Alexei\.nuget\packages\system.componentmodel\4.3.0\ref\netstandard1.0\System.ComponentModel.dll /reference:C:\Users\Alexei\.nuget\packages\system.componentmodel.primitives\4.3.0\ref\netstandard1.0\System.ComponentModel.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\system.componentmodel.typeconverter\4.3.0\ref\netstandard1.5\System.ComponentModel.TypeConverter.dll /reference:C:\Users\Alexei\.nuget\packages\system.console\4.3.0\ref\netstandard1.3\System.Console.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.contracts\4.3.0\ref\netstandard1.0\System.Diagnostics.Contracts.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.debug\4.3.0\ref\netstandard1.3\System.Diagnostics.Debug.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.diagnosticsource\4.3.1\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.process\4.3.0\ref\netstandard1.4\System.Diagnostics.Process.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.stacktrace\4.3.0\ref\netstandard1.3\System.Diagnostics.StackTrace.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.tools\4.3.0\ref\netstandard1.0\System.Diagnostics.Tools.dll /reference:C:\Users\Alexei\.nuget\packages\system.diagnostics.tracing\4.3.0\ref\netstandard1.5\System.Diagnostics.Tracing.dll /reference:C:\Users\Alexei\.nuget\packages\system.dynamic.runtime\4.3.0\ref\netstandard1.3\System.Dynamic.Runtime.dll /reference:C:\Users\Alexei\.nuget\packages\system.globalization.calendars\4.3.0\ref\netstandard1.3\System.Globalization.Calendars.dll /reference:C:\Users\Alexei\.nuget\packages\system.globalization\4.3.0\ref\netstandard1.3\System.Globalization.dll /reference:C:\Users\Alexei\.nuget\packages\system.globalization.extensions\4.3.0\ref\netstandard1.3\System.Globalization.Extensions.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.compression\4.3.0\ref\netstandard1.3\System.IO.Compression.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.compression.zipfile\4.3.0\ref\netstandard1.3\System.IO.Compression.ZipFile.dll /reference:C:\Users\Alexei\.nuget\packages\system.io\4.3.0\ref\netstandard1.5\System.IO.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.filesystem\4.3.0\ref\netstandard1.3\System.IO.FileSystem.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.filesystem.primitives\4.3.0\ref\netstandard1.3\System.IO.FileSystem.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.filesystem.watcher\4.3.0\ref\netstandard1.3\System.IO.FileSystem.Watcher.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.memorymappedfiles\4.3.0\ref\netstandard1.3\System.IO.MemoryMappedFiles.dll /reference:C:\Users\Alexei\.nuget\packages\system.io.unmanagedmemorystream\4.3.0\ref\netstandard1.3\System.IO.UnmanagedMemoryStream.dll /reference:C:\Users\Alexei\.nuget\packages\system.linq\4.3.0\ref\netstandard1.6\System.Linq.dll /reference:C:\Users\Alexei\.nuget\packages\system.linq.expressions\4.3.0\ref\netstandard1.6\System.Linq.Expressions.dll /reference:C:\Users\Alexei\.nuget\packages\system.linq.parallel\4.3.0\ref\netstandard1.1\System.Linq.Parallel.dll /reference:C:\Users\Alexei\.nuget\packages\system.linq.queryable\4.3.0\ref\netstandard1.0\System.Linq.Queryable.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.http\4.3.2\ref\netstandard1.3\System.Net.Http.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.nameresolution\4.3.0\ref\netstandard1.3\System.Net.NameResolution.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.primitives\4.3.0\ref\netstandard1.3\System.Net.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.requests\4.3.0\ref\netstandard1.3\System.Net.Requests.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.security\4.3.1\ref\netstandard1.3\System.Net.Security.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.sockets\4.3.0\ref\netstandard1.3\System.Net.Sockets.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.webheadercollection\4.3.0\ref\netstandard1.3\System.Net.WebHeaderCollection.dll /reference:C:\Users\Alexei\.nuget\packages\system.net.websockets\4.3.0\ref\netstandard1.3\System.Net.WebSockets.dll /reference:C:\Users\Alexei\.nuget\packages\system.numerics.vectors\4.3.0\ref\netstandard1.0\System.Numerics.Vectors.dll /reference:C:\Users\Alexei\.nuget\packages\system.objectmodel\4.3.0\ref\netstandard1.3\System.ObjectModel.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.dispatchproxy\4.3.0\ref\netstandard1.3\System.Reflection.DispatchProxy.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection\4.3.0\ref\netstandard1.5\System.Reflection.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.emit\4.3.0\ref\netstandard1.1\System.Reflection.Emit.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.emit.ilgeneration\4.3.0\ref\netstandard1.0\System.Reflection.Emit.ILGeneration.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.emit.lightweight\4.3.0\ref\netstandard1.0\System.Reflection.Emit.Lightweight.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.extensions\4.3.0\ref\netstandard1.0\System.Reflection.Extensions.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.metadata\1.4.1\lib\netstandard1.1\System.Reflection.Metadata.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.primitives\4.3.0\ref\netstandard1.0\System.Reflection.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\system.reflection.typeextensions\4.3.0\ref\netstandard1.5\System.Reflection.TypeExtensions.dll /reference:C:\Users\Alexei\.nuget\packages\system.resources.reader\4.3.0\lib\netstandard1.0\System.Resources.Reader.dll /reference:C:\Users\Alexei\.nuget\packages\system.resources.resourcemanager\4.3.0\ref\netstandard1.0\System.Resources.ResourceManager.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.compilerservices.unsafe\4.3.0\lib\netstandard1.0\System.Runtime.CompilerServices.Unsafe.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime\4.3.0\ref\netstandard1.5\System.Runtime.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.extensions\4.3.0\ref\netstandard1.5\System.Runtime.Extensions.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.handles\4.3.0\ref\netstandard1.3\System.Runtime.Handles.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.interopservices\4.3.0\ref\netcoreapp1.1\System.Runtime.InteropServices.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.interopservices.runtimeinformation\4.3.0\ref\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.loader\4.3.0\ref\netstandard1.5\System.Runtime.Loader.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.numerics\4.3.0\ref\netstandard1.1\System.Runtime.Numerics.dll /reference:C:\Users\Alexei\.nuget\packages\system.runtime.serialization.primitives\4.3.0\ref\netstandard1.3\System.Runtime.Serialization.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.claims\4.3.0\ref\netstandard1.3\System.Security.Claims.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.cryptography.algorithms\4.3.0\ref\netstandard1.6\System.Security.Cryptography.Algorithms.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.cryptography.encoding\4.3.0\ref\netstandard1.3\System.Security.Cryptography.Encoding.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.cryptography.primitives\4.3.0\ref\netstandard1.3\System.Security.Cryptography.Primitives.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.cryptography.x509certificates\4.3.0\ref\netstandard1.4\System.Security.Cryptography.X509Certificates.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.principal\4.3.0\ref\netstandard1.0\System.Security.Principal.dll /reference:C:\Users\Alexei\.nuget\packages\system.security.principal.windows\4.3.0\ref\netstandard1.3\System.Security.Principal.Windows.dll /reference:C:\Users\Alexei\.nuget\packages\system.text.encoding\4.3.0\ref\netstandard1.3\System.Text.Encoding.dll /reference:C:\Users\Alexei\.nuget\packages\system.text.encoding.extensions\4.3.0\ref\netstandard1.3\System.Text.Encoding.Extensions.dll /reference:C:\Users\Alexei\.nuget\packages\system.text.encodings.web\4.3.1\lib\netstandard1.0\System.Text.Encodings.Web.dll /reference:C:\Users\Alexei\.nuget\packages\system.text.regularexpressions\4.3.0\ref\netcoreapp1.1\System.Text.RegularExpressions.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading\4.3.0\ref\netstandard1.3\System.Threading.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.tasks.dataflow\4.7.0\lib\netstandard1.1\System.Threading.Tasks.Dataflow.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.tasks\4.3.0\ref\netstandard1.3\System.Threading.Tasks.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.tasks.extensions\4.3.0\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.tasks.parallel\4.3.0\ref\netstandard1.1\System.Threading.Tasks.Parallel.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.thread\4.3.0\ref\netstandard1.3\System.Threading.Thread.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.threadpool\4.3.0\ref\netstandard1.3\System.Threading.ThreadPool.dll /reference:C:\Users\Alexei\.nuget\packages\system.threading.timer\4.3.0\ref\netstandard1.2\System.Threading.Timer.dll /reference:C:\Users\Alexei\.nuget\packages\system.xml.readerwriter\4.3.0\ref\netstandard1.3\System.Xml.ReaderWriter.dll /reference:C:\Users\Alexei\.nuget\packages\system.xml.xdocument\4.3.0\ref\netstandard1.3\System.Xml.XDocument.dll /debug- /debug:portable /filealign:512 /nologo /optimize+ /out:obj\Release\netcoreapp1.1\WebApp.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /target:exe /warnaserror- /utf8output /deterministic+ /analyzer:C:\Users\Alexei\.nuget\packages\microsoft.codeanalysis.analyzers\1.1.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll /analyzer:C:\Users\Alexei\.nuget\packages\microsoft.codeanalysis.analyzers\1.1.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll Controllers\DnsController.cs Program.cs Startup.cs "C:\Users\Alexei\AppData\Local\Temp\.NETCoreApp,Version=v1.1.AssemblyAttributes.cs" obj\Release\netcoreapp1.1\\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs obj\Release\netcoreapp1.1\\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs obj\Release\netcoreapp1.1\\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs obj\Release\netcoreapp1.1\WebApp.AssemblyInfo.cs
`

**Comment by siewers** [comment]
I just added `.*csc\.exe.*` as a new RegEx pattern in the settings with the `BuildText` classification type. That took care of the problem.

**Comment by mike-ward** [comment]
Scheduled for v2.7
