### ISSUE TITLE
It crashes VS when "replace all" is performed

### ISSUE THREAD

**Issue by wmjordan** [mike-ward/VSColorOutput#63]
Press Ctrl+H in the editor to open the replace dialog and perform a "Replace all" operation in the whole solution. VS will crash. If we disable this extension, nothing will go wrong.

Both VS 2015, 2017 are affected.

**Comment by mike-ward** [comment]
I do this every day. Could be a collision with another extension (it's happened before).

**Comment by Banner-Keith** [comment]
I also do this regularly and have not had VS crash in either version.

**Comment by wmjordan** [comment]
@mike-ward Thanks for providing information. Maybe it is the case.
What kind of extensions could be potentially conflicting?

**Comment by mike-ward** [comment]
Can't say. There was a time when VSColorOutuput was crashing while building C programs. It was finally run down to another extension by Whole Tomoto (I think that's their name). Once alerted they promptly fixed the issue. Hats off to WT for that. If it were me, I would start with a fresh install of VS with no extensions. Add VSColorOutput and see if it happens. If not, add extensions one by one until it repros. Let me know the results and if it's something I can code around I will.

**Comment by wmjordan** [comment]
Thank you for the information.

I had successfully reproduced the issue and addressed the conflicted extension.
_VSColorOutput_ was conflicting with _Codinion_ (http://www.codinion.com/), an extension providing advanced syntax highlighting.
If I disabled either _VSColorOutput_ or _Codinion_, VS were fine.
