### ISSUE TITLE
VSColorOutput for Visual Studio 2015 no longer available?

### ISSUE THREAD

**Issue by ehuna** [mike-ward/VSColorOutput#64]
Hi,

Awesome extension, great work!

In https://www.visualstudiogallery.msdn.microsoft.com/f4d9c2b5-d6d7-4543-a7a5-2d7ebabc2496 I can only find that it supports 'Visual Studio 2017".

Is there any way to get the older version that worked on Visual Studio 2015?  I just got a new laptop and I'm still working with some older VS 2015 projects that are maintained by some other teams.

Thanks,
Emmanuel

**Comment by mike-ward** [comment]
https://github.com/mike-ward/VSColorOutput/releases/tag/v2.5-Release
