### ISSUE TITLE
VS 2017 crashes if there are build errors

### ISSUE THREAD

**Issue by CYBERRRR** [mike-ward/VSColorOutput#66]
Fresh VS2017 with VSColorOutput installation without any other extensions.

Open any project and remove any ";" at the end of any statement and press build. A few dependencies are build and when it starts building the offending project, VS freezes and moves to "Not responding". Crashes with any of the following project types I've been working on: Winform / ASP.NET / Azure stuff.

**Don't know what error/debug info I can give you to help out with this issue. Do let me know.**

For the last few 2 to 3 months I've been disappointed because if there is a project with any build errors, VS 2017 would freeze, not responding, and I'd have to build it in VS 2015 to find out what the problem was.

Recently I reinstalled it once again and decided to keep it without any additional extensions and it has been working great for the past 1,5 / 2 weeks. Today I remembered that I was missing this extension. I installed it and did a quick sanity check just to be sure if the extension was the culprit and it crashed following the above example.

BTW I love your extension!

Thanks for your work/help!

**Comment by mike-ward** [comment]
It has to be something unique to your environment. If VSColorOutput regularly crashed on build errors I would be skewered and BBQ'ed by irate users already. 😄

**Comment by CYBERRRR** [comment]
Isn't there a log somewhere? I know there's a general VS has crashed log file with xml but it's kinda big and a mess and I don't know what to look for.
