### ISSUE TITLE
Color scheme changes not applied upon VS restart

### ISSUE THREAD

**Issue by gregsdennis** [mike-ward/VSColorOutput#67]
I use a dark theme, so I've lighted a few of the colors to make them more visible.  However, every time I restart VS the colors reset to their default.

When I open the Tools -> Options window and select the VSColorOutput section, all of my settings are still there.  When I close the Options window (without having to change anything), my custom scheme is then applied.

**Comment by mike-ward** [comment]
OK, usual questions. What version? What VS and version? What OS? 

Also, check %AppData%/VSColorOutput/vscoloroutput.json to see if your changes are saved there.

**Comment by gregsdennis** [comment]
Sorry, I assume everyone stays up to date.

I'm running VS 2017 on Win10.  I'm on the latest updates, but the problem's been there with all of the updates.

Not sure it matters, but my Win10 is running on a Parallels VM on a Mac.

I don't have access to the file at the moment, so I'll update later, but the settings *are* saved, I just have to open the Options windows to have them apply.

**Comment by mike-ward** [comment]
>Not sure it matters, but my Win10 is running on a Parallels VM on a Mac.
Maybe it does.

**Comment by gregsdennis** [comment]
To confirm, the file is there.

**Comment by general-adhoc** [comment]
I am having this same issue as well.  Windows 10 (not Parallels or any VM), VS 2017 15.6.4, VSColorOutput v 2.5.1.

By default, info logs are dark blue, which on a dark grey background are very difficult to see.  In options I have info set to light blue.  When I open the VSColorOutput options window, and then close, the settings are immediately applied, correctly coloring the output window.

Restart Visual Studio, and these settings are no longer applied, and you have to go back in to Tools -> Options -> VsColorOutput -> General.  Any idea what is causing this problem @mike-ward ?

Thank you for your work on this great extension BTW!

**Comment by gregsdennis** [comment]
I haven't had this issue in a long time.  Closing.
