### ISSUE TITLE
Files like "error.cpp" get misinterpreted as errors

### ISSUE THREAD

**Issue by dan-masek** [mike-ward/VSColorOutput#7]
The default regex with index 3 is `(\W|^)(error|fail|failed|exception)\W`, which treats lines containing text such as "error.cpp" since '.' is not a word character.

This can be avoided by using an expression such as `(\W|^)(error|fail|failed|exception)[^\w\.]`

**Comment by mike-ward** [comment]
Thanks!

**Comment by mike-ward** [comment]
Fixed in beta 1
