### ISSUE TITLE
LiveUnitTesting result Color

### ISSUE THREAD

**Issue by JakobFerdinand** [mike-ward/VSColorOutput#72]
**Hi,**

When using Live Unit Testing in VS2017 the Test Results are always displayed in Red, no matter if there was a failing Test or not.
![image](https://user-images.githubusercontent.com/16666458/38489208-f8617b24-3be5-11e8-9381-5f68b4ffb17a.png)

Would be great to color the Succeeded once in Green, if there was a skipped test in Yellow and when there was a failed test in Red!

Thank you for the great tool!

**Comment by mike-ward** [comment]
You can adjust the regular expressions to suit your needs.

**Comment by JakobFerdinand** [comment]
**Great Thank you!**

I added this two entries at front:

- RegExPattern: `Finished executing tests\. \(Passed\: \d+, Failed\: 0, Skipped: [^0]\d*, Not Executed: \d+\)` ClassificationType: `LogWarning`
- RegExPattern: `Finished executing tests\. \(Passed\: [^0]\d*, Failed\: 0, Skipped: 0, Not Executed: 0\)` ClassificationType: `BuildHead`

![image](https://user-images.githubusercontent.com/16666458/38683766-889cc43e-3e6e-11e8-9ab0-b3636913123a.png)

**Comment by mike-ward** [comment]
Looks good!
