### ISSUE TITLE
2.6.5 Not working with Visual Studio 2017

### ISSUE THREAD

**Issue by BigSeb** [mike-ward/VSColorOutput#86]
I have tried Release 2.6.5 and it no longer loads in Visual Studio 2017 (15.9.11). Looking at the ActivityLog.xml file and we get the following error:

> Description: Could not load file or assembly Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a or one of its dependencies

This is most likely due to the recent change in the build system or AsyncPackage support.

I am able to load the extension in Visual Studio 2019 though.

**Comment by mike-ward** [comment]
Fixed the manifest. You'll have uninstall and download the updated extension.

**Comment by johnendev** [comment]
The extension can't be installed in vs2017 as it's no longer listed now. Have to download the vsix from the releases page here on github instead.

**Comment by jnpwly** [comment]
Just to make it exceedingly obvious, for people like me that failed to understand this... 

* you have in uninstall the existing version from your machine
* you have to download a *previous* version (2.6.4) from here: https://github.com/mike-ward/VSColorOutput/releases/tag/v2.6.4, 
* and then install this newly downloaded version. 

Then magic happens, and it all works.

**Comment by MattyBoy4444** [comment]
We have both VS2017 and VS2019 installed.  Is there any way to have it work with both versions?

**Comment by leftos** [comment]
> We have both VS2017 and VS2019 installed. Is there any way to have it work with both versions?

Same question. I manually installed 2.6.4 and yet Visual Studio 2017 (or is it that I also have 2019 installed?) auto-updated the extension back to 2.6.5 and now it's stopped working again in 2017.

**Comment by jnpwly** [comment]
@leftos -- with regards specifically to VS2017, you might need to uninstall it again, and reinstall the 2.6.4 version downloaded from GitHub. I have then gone into the Tools > Extensions and Updates... dialog, found the entry for VSColorOutput and turned *off* the automatic updates:

![2019-04-18_9-34-19](https://user-images.githubusercontent.com/10701621/56322603-9d764d80-61bd-11e9-9649-0314debbad75.png)

I don't know how that would work with VS2019 though.

Thanks @mike-ward for a great extension.

**Comment by mike-ward** [comment]
I'll see what I can do about 2017 support this weekend. It may be as easy as rebuilding in VS 2017. The issue is there were some upcoming changes in 2019 16.1 the required attention. The tooling has changed and they have mercifully fixed the issue with dependencies by packaging them all up in a single Nuget package.

What I find weird is the that VS 2017 is auto-updating a package clearly marked for VS 2019 only in the manifest.
