### ISSUE TITLE
VisualStudio 2017 not supported anymore

### ISSUE THREAD

**Issue by ldecarufel** [mike-ward/VSColorOutput#89]
The latest version of VSColorOutput (2.6.5) doesn't seem to support VS2017 anymore.

The extension was auto-updated on my machine and stopped working.

Trying to re-install the latest version wasn't possible because it supports only VS2019.

I had to install an older version (2.6.4) and disable auto updates.

Is this behavior normal?  Why stop supporting 2017?

**Comment by jacobrillema** [comment]
+1 would like 2017 support back

**Comment by MagicAndre1981** [comment]
the dev stopped 2017 support here:

https://github.com/mike-ward/VSColorOutput/commit/70beddc177e9b1de427aea908fe55bb69e127555

**Comment by mike-ward** [comment]
I tried rebuilding in VS 2017 but it didn't work. The new packages, references seem to only be for VS 2019.

Marking the manifest as 2019 only should keep it from auto-updating VS 2017 now.

**Comment by MagicAndre1981** [comment]
[downgrade the VSSDK packages](https://github.com/mike-ward/VSColorOutput/commit/70beddc177e9b1de427aea908fe55bb69e127555#commitcomment-33297890) to support VS2017 again
