### ISSUE TITLE
Support for Visual Studio Code

### ISSUE THREAD

**Issue by jamespharvey20** [mike-ward/VSColorOutput#90]
Wondering if you've considered adding support for Visual Studio Code.  I'll admit I have no idea how big of differences there are writing extensions for the two.  I'd love to be able to use this again, after having switched over to Code a long time ago!

**Comment by mike-ward** [comment]
Thought about it but the issue for me is I don't use Visual Studio Code. That's mostly because I'm a .NET developer and find the older Visual Studio IDE to work better in that environment.
