### ISSUE TITLE
Extensions and Updates search for VSColorOutput doesn't yield it

### ISSUE THREAD

**Issue by aderesh** [mike-ward/VSColorOutput#92]
Hi,

When I open 'Extension and Updates' dialog box and search for VSColorOutput, it doesn't show me the extension, it shows 'MetaProject' extension. Created this issue just in case it's related to the plugins metadata. 

![image](https://user-images.githubusercontent.com/2285614/63629784-5f14f300-c5e2-11e9-8b47-b6d0eebda496.png)

P.S. Love the extension, thanks!

**Comment by mike-ward** [comment]
Which version of Visual Studio? The current VSColorOutput release only supports VS 2019 so maybe it's a gallery issue.
