### ISSUE TITLE
Does not work with VS2017 (15.9.15)

### ISSUE THREAD

**Issue by LaoR-UA** [mike-ward/VSColorOutput#93]
Hi. This package fails to load Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
See error in attached file.
[Error.txt](https://github.com/mike-ward/VSColorOutput/files/3551628/Error.txt)

**Comment by CADbloke** [comment]
Workaround: Revert to https://github.com/mike-ward/VSColorOutput/releases/tag/v2.6.4
