### ISSUE TITLE
Broken colors after upgrade VS to 16.3.4

### ISSUE THREAD

**Issue by wtywtykk** [mike-ward/VSColorOutput#97]
Hi,
    After upgrading vs to 16.3.4, the colors in the text editor are broken. Disabling this extension fixs the problem.
![image](https://user-images.githubusercontent.com/13284789/66710448-f872b100-edaa-11e9-811d-ac456f5cf4cf.png)

**Comment by wtywtykk** [comment]
I'm not sure what caused the problem now, because the problem emerged again somehow with this extension disabled.

**Comment by mike-ward** [comment]
I'm see odd behavior in syntax highlighting in the text editor as well. Seems like lately the updates have been a bit jarring introducing behavior changes that come and go.
